# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{seamusabshere-daemon-spawn}
  s.version = "0.2.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Vollmer"]
  s.date = %q{2010-07-13}
  s.description = %q{gem 0.3.0 re-release... originally at http://github.com/alexvollmer/daemon-spawn}
  s.email = %q{seamus@abshere.net}
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    ".autotest",
     ".gitignore",
     "History.txt",
     "Manifest.txt",
     "README.txt",
     "Rakefile",
     "VERSION",
     "daemon-spawn.gemspec",
     "lib/daemon_spawn.rb",
     "seamusabshere-daemon-spawn.gemspec",
     "test/daemon_spawn_test.rb",
     "test/multi_daemon_spawn_test.rb",
     "test/servers/echo_server.rb",
     "test/servers/simple_server.rb"
  ]
  s.homepage = %q{http://github.com/seamusabshere/daemon-spawn}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A simple, flexible daemon management library. (re-released by Seamus Abshere)}
  s.test_files = [
    "test/daemon_spawn_test.rb",
     "test/multi_daemon_spawn_test.rb",
     "test/servers/echo_server.rb",
     "test/servers/simple_server.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

